///**
// * Autogenerated by Avro
// *
// * DO NOT EDIT DIRECTLY
// */
//package com.springconfluent.schema;
//
//import org.apache.avro.specific.SpecificData;
//import org.apache.avro.message.BinaryMessageEncoder;
//import org.apache.avro.message.BinaryMessageDecoder;
//import org.apache.avro.message.SchemaStore;
//
//@SuppressWarnings("all")
//@org.apache.avro.specific.AvroGenerated
//public class Event extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
//  private static final long serialVersionUID = 2243370682298242917L;
//  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event\",\"namespace\":\"com.springconfluent.schema\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]}");
//  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
//
//  private static SpecificData MODEL$ = new SpecificData();
//
//  private static final BinaryMessageEncoder<Event> ENCODER =
//      new BinaryMessageEncoder<Event>(MODEL$, SCHEMA$);
//
//  private static final BinaryMessageDecoder<Event> DECODER =
//      new BinaryMessageDecoder<Event>(MODEL$, SCHEMA$);
//
//  /**
//   * Return the BinaryMessageDecoder instance used by this class.
//   */
//  public static BinaryMessageDecoder<Event> getDecoder() {
//    return DECODER;
//  }
//
//  /**
//   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
//   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
//   */
//  public static BinaryMessageDecoder<Event> createDecoder(SchemaStore resolver) {
//    return new BinaryMessageDecoder<Event>(MODEL$, SCHEMA$, resolver);
//  }
//
//  /** Serializes this Event to a ByteBuffer. */
//  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
//    return ENCODER.encode(this);
//  }
//
//  /** Deserializes a Event from a ByteBuffer. */
//  public static Event fromByteBuffer(
//      java.nio.ByteBuffer b) throws java.io.IOException {
//    return DECODER.decode(b);
//  }
//
//  @Deprecated public java.lang.CharSequence message;
//
//  /**
//   * Default constructor.  Note that this does not initialize fields
//   * to their default values from the schema.  If that is desired then
//   * one should use <code>newBuilder()</code>.
//   */
//  public Event() {}
//
//  /**
//   * All-args constructor.
//   * @param message The new value for message
//   */
//  public Event(java.lang.CharSequence message) {
//    this.message = message;
//  }
//
//  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
//  // Used by DatumWriter.  Applications should not call.
//  public java.lang.Object get(int field$) {
//    switch (field$) {
//    case 0: return message;
//    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
//    }
//  }
//
//  // Used by DatumReader.  Applications should not call.
//  @SuppressWarnings(value="unchecked")
//  public void put(int field$, java.lang.Object value$) {
//    switch (field$) {
//    case 0: message = (java.lang.CharSequence)value$; break;
//    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
//    }
//  }
//
//  /**
//   * Gets the value of the 'message' field.
//   * @return The value of the 'message' field.
//   */
//  public java.lang.CharSequence getMessage() {
//    return message;
//  }
//
//  /**
//   * Sets the value of the 'message' field.
//   * @param value the value to set.
//   */
//  public void setMessage(java.lang.CharSequence value) {
//    this.message = value;
//  }
//
//  /**
//   * Creates a new Event RecordBuilder.
//   * @return A new Event RecordBuilder
//   */
//  public static com.springconfluent.schema.Event.Builder newBuilder() {
//    return new com.springconfluent.schema.Event.Builder();
//  }
//
//  /**
//   * Creates a new Event RecordBuilder by copying an existing Builder.
//   * @param other The existing builder to copy.
//   * @return A new Event RecordBuilder
//   */
//  public static com.springconfluent.schema.Event.Builder newBuilder(com.springconfluent.schema.Event.Builder other) {
//    return new com.springconfluent.schema.Event.Builder(other);
//  }
//
//  /**
//   * Creates a new Event RecordBuilder by copying an existing Event instance.
//   * @param other The existing instance to copy.
//   * @return A new Event RecordBuilder
//   */
//  public static com.springconfluent.schema.Event.Builder newBuilder(com.springconfluent.schema.Event other) {
//    return new com.springconfluent.schema.Event.Builder(other);
//  }
//
//  /**
//   * RecordBuilder for Event instances.
//   */
//  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event>
//    implements org.apache.avro.data.RecordBuilder<Event> {
//
//    private java.lang.CharSequence message;
//
//    /** Creates a new Builder */
//    private Builder() {
//      super(SCHEMA$);
//    }
//
//    /**
//     * Creates a Builder by copying an existing Builder.
//     * @param other The existing Builder to copy.
//     */
//    private Builder(com.springconfluent.schema.Event.Builder other) {
//      super(other);
//      if (isValidValue(fields()[0], other.message)) {
//        this.message = data().deepCopy(fields()[0].schema(), other.message);
//        fieldSetFlags()[0] = true;
//      }
//    }
//
//    /**
//     * Creates a Builder by copying an existing Event instance
//     * @param other The existing instance to copy.
//     */
//    private Builder(com.springconfluent.schema.Event other) {
//            super(SCHEMA$);
//      if (isValidValue(fields()[0], other.message)) {
//        this.message = data().deepCopy(fields()[0].schema(), other.message);
//        fieldSetFlags()[0] = true;
//      }
//    }
//
//    /**
//      * Gets the value of the 'message' field.
//      * @return The value.
//      */
//    public java.lang.CharSequence getMessage() {
//      return message;
//    }
//
//    /**
//      * Sets the value of the 'message' field.
//      * @param value The value of 'message'.
//      * @return This builder.
//      */
//    public com.springconfluent.schema.Event.Builder setMessage(java.lang.CharSequence value) {
//      validate(fields()[0], value);
//      this.message = value;
//      fieldSetFlags()[0] = true;
//      return this;
//    }
//
//    /**
//      * Checks whether the 'message' field has been set.
//      * @return True if the 'message' field has been set, false otherwise.
//      */
//    public boolean hasMessage() {
//      return fieldSetFlags()[0];
//    }
//
//
//    /**
//      * Clears the value of the 'message' field.
//      * @return This builder.
//      */
//    public com.springconfluent.schema.Event.Builder clearMessage() {
//      message = null;
//      fieldSetFlags()[0] = false;
//      return this;
//    }
//
//    @Override
//    @SuppressWarnings("unchecked")
//    public Event build() {
//      try {
//        Event record = new Event();
//        record.message = fieldSetFlags()[0] ? this.message : (java.lang.CharSequence) defaultValue(fields()[0]);
//        return record;
//      } catch (java.lang.Exception e) {
//        throw new org.apache.avro.AvroRuntimeException(e);
//      }
//    }
//  }
//
//  @SuppressWarnings("unchecked")
//  private static final org.apache.avro.io.DatumWriter<Event>
//    WRITER$ = (org.apache.avro.io.DatumWriter<Event>)MODEL$.createDatumWriter(SCHEMA$);
//
//  @Override public void writeExternal(java.io.ObjectOutput out)
//    throws java.io.IOException {
//    WRITER$.write(this, SpecificData.getEncoder(out));
//  }
//
//  @SuppressWarnings("unchecked")
//  private static final org.apache.avro.io.DatumReader<Event>
//    READER$ = (org.apache.avro.io.DatumReader<Event>)MODEL$.createDatumReader(SCHEMA$);
//
//  @Override public void readExternal(java.io.ObjectInput in)
//    throws java.io.IOException {
//    READER$.read(this, SpecificData.getDecoder(in));
//  }
//
//}
